apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls
  namespace: traefik
spec:
  secretName: argocd-tls-secret
  duration: 8760h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - argocd.local
  issuerRef:
    name: lab-ca
    kind: ClusterIssuer
    group: cert-manager.io
